// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/records.ts";
import * as $$$$$$$$$$$1 from "./apps/decohub.ts";
import * as $$$$$$$$$$$2 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/BlogPosts.tsx";
import * as $$$$$$1 from "./sections/Carousel.tsx";
import * as $$$$$$2 from "./sections/CollapseGroup.tsx";
import * as $$$$$$3 from "./sections/DetailedCarousel.tsx";
import * as $$$$$$4 from "./sections/Faq.tsx";
import * as $$$$$$5 from "./sections/Footer.tsx";
import * as $$$$$$6 from "./sections/Header.tsx";
import * as $$$$$$7 from "./sections/Hero.tsx";
import * as $$$$$$8 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$9 from "./sections/Logos.tsx";
import * as $$$$$$10 from "./sections/MainHero.tsx";
import * as $$$$$$11 from "./sections/Plans.tsx";
import * as $$$$$$12 from "./sections/TcoCalculator.tsx";
import * as $$$$$$13 from "./sections/Testimonials.tsx";
import * as $$$$$$14 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/BlogPosts.tsx": $$$$$$0,
    "site/sections/Carousel.tsx": $$$$$$1,
    "site/sections/CollapseGroup.tsx": $$$$$$2,
    "site/sections/DetailedCarousel.tsx": $$$$$$3,
    "site/sections/Faq.tsx": $$$$$$4,
    "site/sections/Footer.tsx": $$$$$$5,
    "site/sections/Header.tsx": $$$$$$6,
    "site/sections/Hero.tsx": $$$$$$7,
    "site/sections/ImageWithParagraph.tsx": $$$$$$8,
    "site/sections/Logos.tsx": $$$$$$9,
    "site/sections/MainHero.tsx": $$$$$$10,
    "site/sections/Plans.tsx": $$$$$$11,
    "site/sections/TcoCalculator.tsx": $$$$$$12,
    "site/sections/Testimonials.tsx": $$$$$$13,
    "site/sections/Theme/Theme.tsx": $$$$$$14,
  },
  "apps": {
    "site/apps/deco/records.ts": $$$$$$$$$$$0,
    "site/apps/decohub.ts": $$$$$$$$$$$1,
    "site/apps/site.ts": $$$$$$$$$$$2,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
